# Generated by Django 5.1.4 on 2024-12-08 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mess',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'is_manager': True}, on_delete=django.db.models.deletion.CASCADE, related_name='messes', to=settings.AUTH_USER_MODEL),
        ),
    ]
