# Generated by Django 5.1.4 on 2024-12-08 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_mess_created_at_alter_mess_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='mess',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_messes', to=settings.AUTH_USER_MODEL),
        ),
    ]
